---
- name: Create app network
  docker_network:
    name: app_net
    state: present

- name: Create proxy network
  docker_network:
    name: nginx-proxy
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3
