- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - docker
    - create_network
    - launch_database
    - launch_app
    - launch_proxy
   # - front 