name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
    - main
    - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
     #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4

     #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file ./TP1/simpleapi/pom.xml
      
      - name: SonarCloud Analysis
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=laurab21_DevOps-1 -Dsonar.organization=laurab21 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./TP1/simpleapi/pom.xml

    
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image for backend
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/simpleapi
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build Docker image for httpd
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/http-server
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apache-landingpage:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build Docker image for postgres
        uses: docker/build-push-action@v6
        with:
          context: ./TP1
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1-postgres:latest
          push: ${{ github.ref == 'refs/heads/main' }}

  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to server with Ansible
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/DevOps-1/TP1/ansible
            git pull origin main
            /opt/homebrew/bin/ansible-playbook -i inventories/setup.yml playbook.yml


          

